version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - # Build command 1
      - # Build command 2
      - # ...

artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules
    - # ... any other output files